>>> %Run interfata_AVC.py
Traceback (most recent call last):
  File "/home/aaa/aaa/facial-recognition-updated/Face Recognition/interfata_AVC.py", line 178, in <module>
    app = FacialRecognitionApp(root)
  File "/home/aaa/aaa/facial-recognition-updated/Face Recognition/interfata_AVC.py", line 47, in __init__
    command=self.start_recognition_thread
AttributeError: 'FacialRecognitionApp' object has no attribute 'start_recognition_thread'